#!/usr/bin/env bash

# Pull all submodules
git submodule init && git submodule update --recursive

# List changed files
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_file() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# `npm install` and `npm prune` if the `package.json` file gets changed
check_file "package.json" "npm install && npm prune && npm dedupe"
