sudo: true
language: node_js
notifications:
  email: "devs@scrollback.io"
cache:
  directories:
    - node_modules
node_js:
  - 'stable'
before_script:
  - echo '{}' > config/server.json
  - echo '{}' > config/client.json
  - npm run flow -- check
  - npm run build
after_success:
  - npm run coverage
